name: BirthdayNotes

on: [push]

jobs:
  build:
    name: BirthdayNotes
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Compile C++ Code
        run: g++ *.cpp -o BirthdayNotes

      - name: Run Tests
        run: ./BirthdayNotes -test
