name: Lint Code Base

on:
  push:
    branches-ignore: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Clang
        uses: actions/setup-clang@v1
        with:
          llvm-version: '12'

      - name: Run Clang-Tidy
        run: |
          clang-tidy --version
          clang-tidy src/*.cpp -checks=* -- -Iinclude
