name: Lint Code Base

on: [pull_request]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    
    steps:
      - name: c-linter
        uses: ArtificialAmateur/cpp-linter-action@master
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
